version: "3"

services:
  dashboard:
    build: ./dashboard
    restart: always
    command:
      "npm run build && npm run start"
    env_file:
      - "environment.env"
    labels:
      - "traefik.frontend.rule=Host:${DASHBOARD_HOST}"
      - "traefik.port=3000"

  driver:
    build: ./driver
    restart: always
    command:
      "npm run build && npm run start"
    env_file:
      - "environment.env"
    labels:
      - "traefik.frontend.rule=Host:${DRIVER_HOST}"
      - "traefik.port=3000"

  user:
    build: ./user
    restart: always
    command:
      "npm run build && npm run start"
    env_file:
      - "environment.env"
    labels:
      - "traefik.frontend.rule=Host:${USER_HOST}"
      - "traefik.port=3000"


  api:
    build: ./api
    restart: always
    command:
      "npm run serve"
    env_file:
      - "environment.env"
    labels:
      - "traefik.frontend.rule=Host:${API_HOST}"
      - "traefik.port=1337"
    depends_on:
      - mongo

  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./.mongo_database:/data/db

  reverse-proxy:
    image: traefik
    command: --docker
    ports:
      - "80:80"
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
