version: "3"

services:
  dashboard:
    restart: always
    image: node:11-alpine
    working_dir: "/var/www/app"
    networks:
      - web
      - default
    environment:
      - HOST=0.0.0.0
    command: sh -c "rm package-lock.json || npm i --only=production && npm run build && npm run start"
    env_file:
      - "environment.env"
    volumes:
      - "./dashboard:/var/www/app"
    labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:${DASHBOARD_HOST}"
      - "traefik.port=3000"
      - "traefik.protocol=http"

  driver:
    restart: always
    image: node:11-alpine
    working_dir: "/var/www/app"
    networks:
      - web
      - default
    environment:
      - HOST=0.0.0.0
    command: sh -c "npm i --only=production && npm run build && npm run start"
    env_file:
      - "environment.env"
    volumes:
      - "./driver:/var/www/app"
    labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:${DRIVER_HOST}"
      - "traefik.port=3000"
      - "traefik.protocol=http"

  user:
    restart: always
    image: node:11-alpine
    working_dir: "/var/www/app"
    networks:
      - web
      - default
    environment:
      - HOST=0.0.0.0
    command: sh -c "npm i --only=production && npm run build && npm run start"
    env_file:
      - "environment.env"
    volumes:
      - "./user:/var/www/app"
    labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:${USER_HOST}"
      - "traefik.port=3000"
      - "traefik.protocol=http"

  api:
    build: ./api
    restart: always
    command:
      "npm run serve"
    env_file:
      - "environment.env"
    labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:${API_HOST}"
      - "traefik.port=1337"
      - "traefik.protocol=http"
    depends_on:
      - mongo
    networks:
      - web
      - default

  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./.mongo_database:/data/db
    labels:
      - "traefik.enable=false"

  reverse-proxy:
    image: traefik:alpine
    command: --docker
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/traefik.toml:/traefik.toml
      - ./traefik/acme.json:/acme.json
    labels:
      - "traefik.enable=false"
    networks:
      - web
networks:
  web:
    external: true
