apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: "{{ include "backup.fullname" . }}-cleaner"
  labels:
{{ include "backup.labels" . | indent 4 }}
spec:
  schedule: "{{ .Values.job.frequency }}"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: '{{ include "backup.fullname" . }}-cleaner'
              image: "{{ .Values.cleanImage.repository }}:{{ .Values.cleanImage.tag }}"
              imagePullPolicy: {{ .Values.cleanImage.pullPolicy }}
              command: ["/bin/sh"]
              args:
                - "-c"
                - >
                  apk add --update httpie
                  && export ACCESS_TOKEN=`http --ignore-stdin --headers --json https://auth.cloud.ovh.net/v3/auth/tokens
                  auth:='{"identity":{"methods":["password"],"password":{"user":
                  {"domain":{"id":"default"},"name":"{{ .Values.swift.user }}","password":
                  "{{ .Values.swift.password }}"}}},"scope":{"project":{"domain":{"id":"default"},"name":
                  "{{ .Values.swift.tenant }}"}}}' | awk '/X-Subject-Token/ {print $2}'`
                  && for fileDate in `http --ignore-stdin GET {{ .Values.swift.url }}/ X-Auth-Token:$ACCESS_TOKEN
                  | awk -F '.' '{print $2}' | xargs date-filter`; do http --ignore-stdin DELETE
                  {{ .Values.swift.url }}/{{ .Values.swift.prefix }}.$fileDate.archive X-Auth-Token:$ACCESS_TOKEN; done
          restartPolicy: OnFailure