# source https://github.com/helm/charts/blob/master/stable/grafana/values.yaml
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        access: proxy
        type: prometheus
        url: http://prometheus-operated:9090
        isDefault: true
      - name: Loki
        access: proxy
        type: loki
        url: http://loki:3100
