# ref https://github.com/helm/charts/blob/master/stable/mongodb/values.yaml
mongodbUsername: e-chauffeur
mongodbDatabase: e-chauffeur

replicaSet:
  enabled: true
  name: rs0
  replicas:
    secondary: 1
    arbiter: 1
persistence:
  enabled: true
  size: 15Gi

## Prometheus Exporter / Metrics ##
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    additionalLabels:
      release: prometheus
